name: 02.GetKeyVaultSecrets

on:
  workflow_call:
    outputs:
      ConnectionStringDevdgwsamplesstorage:
        description: 'ConnectionStringDevdgwsamplesstorage'
        value: ${{ jobs.main.outputs.ConnectionStringDevdgwsamplesstorage }}
      AppSettings_BlobstorageConnectionString:
        description: 'AppSettings_BlobstorageConnectionString'
        value: ${{ jobs.main.outputs.AppSettings_BlobstorageConnectionString }}

jobs:
  main:
    runs-on: self-hosted
    outputs:
      ConnectionStringDevdgwsamplesstorage: ${{ steps.get_keyvault_secrets.outputs.ConnectionStringDevdgwsamplesstorage }}
      AppSettings_BlobstorageConnectionString: ${{ steps.get_keyvault_secrets.outputs.AppSettings_BlobstorageConnectionString }}

    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY_V3 }}

    steps:

      - name: Azure CLI Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get KeyVault Secrets
        id: get_keyvault_secrets
        run: |
          $env:ConnectionStringDevdgwsamplesstorage=$(az keyvault secret show --vault-name dev-dgw-001-kv --name ConnectionStringDevdgwsamplesstorage --query value -o tsv)
          $env:AppSettings_BlobstorageConnectionString=$(az keyvault secret show --vault-name dev-dgw-001-kv --name AppSettings--BlobstorageConnectionString --query value -o tsv)
          # Write-Host "ConnectionStringDevdgwsamplesstorage=$env:ConnectionStringDevdgwsamplesstorage"
          # Write-Host "AppSettings_BlobstorageConnectionString=$env:AppSettings_BlobstorageConnectionString"
          echo "::set-output name=ConnectionStringDevdgwsamplesstorage::$env:ConnectionStringDevdgwsamplesstorage"
          echo "::set-output name=AppSettings_BlobstorageConnectionString::$env:AppSettings_BlobstorageConnectionString"

      - name: Set KeyVault Secrets as Environment Variables
        run: |
          echo "Setting environment variables..."
          echo "ConnectionStringDevdgwsamplesstorage=${{ steps.get_keyvault_secrets.outputs.ConnectionStringDevdgwsamplesstorage }}" >> $GITHUB_ENV
          echo "AppSettings_BlobstorageConnectionString=${{ steps.get_keyvault_secrets.outputs.AppSettings_BlobstorageConnectionString }}" >> $GITHUB_ENV
